version: "3.3"
services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - "home/app/node_modules"
      - "./:/home/app"
